version: "3.3"

services:

  db:
    container_name: tarefas
    image: mysql:5.7
    expose:
      - "3306"
    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD_MYSQL}
      MYSQL_DATABASE: ${NAME_MYSQL}

  app:
    container_name: app
    build: .
    image: django-docker:0.0.1
    command: [ "./run_web.sh" ]

    ports:
      - "8000:8000"

    depends_on:
      - db
